SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    completed_at date,
    created_at timestamp(6) without time zone,
    favourite boolean NOT NULL,
    image_url character varying(255),
    notes character varying(255),
    platform character varying(255),
    rating double precision,
    rawg_id bigint,
    release_date date,
    status character varying(255),
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT games_status_check CHECK (((status)::text = ANY ((ARRAY['WISHLIST'::character varying, 'BACKLOG'::character varying, 'PLAYING'::character varying, 'COMPLETED'::character varying, 'DROPPED'::character varying, 'ONLINE'::character varying])::text[])))
);


--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movies (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    original_title character varying(255),
    poster character varying(255),
    release_date date,
    status character varying(255),
    title character varying(255),
    tmdb_id bigint
);


--
-- Name: movies_genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movies_genres (
    movie_id bigint NOT NULL,
    genre_name character varying(255)
);


--
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movies_vod_providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movies_vod_providers (
    movie_id bigint NOT NULL,
    provider_name character varying(255)
);


--
-- Name: seasons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seasons (
    id bigint NOT NULL,
    air_date date,
    episode_count integer NOT NULL,
    name character varying(255),
    rating double precision,
    season_number integer NOT NULL,
    watched_count integer NOT NULL,
    series_id bigint
);


--
-- Name: seasons_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seasons_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: series; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.series (
    id bigint NOT NULL,
    first_air_date date,
    last_air_date date,
    name character varying(255),
    number_of_episodes integer NOT NULL,
    number_of_seasons integer NOT NULL,
    poster_path character varying(255),
    status character varying(255),
    tmdb_id bigint,
    tracking_type character varying(255),
    updated_at timestamp(6) without time zone,
    CONSTRAINT series_tracking_type_check CHECK (((tracking_type)::text = ANY ((ARRAY['WATCHING'::character varying, 'UP_TO_DATE'::character varying, 'COMPLETED'::character varying, 'ON_HOLD'::character varying, 'DROPPED'::character varying, 'WISHLIST'::character varying])::text[])))
);


--
-- Name: series_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.series_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tvseries_vod_providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tvseries_vod_providers (
    tvseries_id bigint NOT NULL,
    provider_name character varying(255)
);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- Name: seasons seasons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seasons
    ADD CONSTRAINT seasons_pkey PRIMARY KEY (id);


--
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);


--
-- Name: games ukbp4g84ptde32bofhj0k7apphk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT ukbp4g84ptde32bofhj0k7apphk UNIQUE (rawg_id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: tvseries_vod_providers fkdcbgi0hrx8jcca66ke16edji0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tvseries_vod_providers
    ADD CONSTRAINT fkdcbgi0hrx8jcca66ke16edji0 FOREIGN KEY (tvseries_id) REFERENCES public.series(id);


--
-- Name: seasons fkh1pirq6juf6a9jpsxjtfbam6x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seasons
    ADD CONSTRAINT fkh1pirq6juf6a9jpsxjtfbam6x FOREIGN KEY (series_id) REFERENCES public.series(id);


--
-- Name: movies_genres fkk0w7fx0a7flrtafppanyup87d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movies_genres
    ADD CONSTRAINT fkk0w7fx0a7flrtafppanyup87d FOREIGN KEY (movie_id) REFERENCES public.movies(id);


--
-- Name: movies_vod_providers fkmcyra4gvl4d3ed2777q30yuqx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movies_vod_providers
    ADD CONSTRAINT fkmcyra4gvl4d3ed2777q30yuqx FOREIGN KEY (movie_id) REFERENCES public.movies(id);
