spring:
  application:
    name: The Library
  datasource:
    url: jdbc:postgresql://localhost:5432/thelibrarydb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    schemas: public
  main:
    banner-mode: off
  jackson:
    time-zone: Europe/Warsaw

server:
  port: 8080

rawg:
  api:
    url: ${RAWG_API_URL}
    key: ${RAWG_API_KEY}
    timeoutInSeconds: 10

tmdb:
  api:
    key: ${TMDB_API_KEY}
    url: ${TMDB_API_URL}
    timeoutInSeconds: 10

igdb:
  api:
    base-url: ${IGDB_API_URL}
    client-id: ${IGDB_CLIENT_ID}
    timeoutInSeconds: 10

  auth:
    token-url: ${IGDB_AUTH_TOKEN_URL}
    client-id: ${IGDB_CLIENT_ID}
    client-secret: ${IGDB_CLIENT_SECRET}
